global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: 'metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']

  - job_name: 'my_application'
    metrics_path: '/api/v1/app-metrics'
    static_configs:
      - targets: ['172.18.88.104:4000']