import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Header from "~/components/core/header";
import SideBar from "~/components/core/side-bar";
import RecentPosts from "~/components/core/recent-posts";
import "./globals.css";
import {Separator} from "~/components/ui/separator";
import {ClerkProvider} from "@clerk/nextjs";
import Posts from "~/components/posts/posts";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
            <html lang="en">
            <body className={`${inter.className} bg-[#010409]`}>
            <Header/>
            <Separator className={'hidden md:block bg-[#403A3A]'}/>
            <div className={'md:grid lg:grid-cols-5 grid-cols-4 px-4'}>
                <SideBar/>
                <div className={'lg:col-span-3 col-span-2'}>
                    {children}
                    <Posts/>
                </div>
                <div className={'hidden md:flex px-2'}>
                    <RecentPosts/>
                </div>
            </div>
            </body>
            </html>
        </ClerkProvider>
    );
}
