import Header from "~/components/core/header";

import "~/styles/globals.css";

import {Inter} from "next/font/google";

import {TRPCReactProvider} from "~/trpc/react";
import SideBar from "~/components/core/side-bar";
import React from "react";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
            <Header/>
            <div className={'md:grid lg:grid-cols-5 grid-cols-4'}>
                <div className={'hidden md:flex'}></div>
                <div className={'lg:col-span-3 col-span-2'}>
                    {children}
                </div>
                <SideBar/>
            </div>
        </TRPCReactProvider>
        </body>
        </html>
    );
}
